### ISSUE TITLE
Question about RAVOS

### ISSUE THREAD

**Issue by yahooo-m** [bo-miao/SgMg#10]
Hi, sorry to ask the question here. I have read the paper about RAVOS. When will the code released?

**Comment by bo-miao** [comment]
Hi, thanks for your interest. That work was done about 3 years ago, its performance is no longer state-of-the-art, so I do not plan to spend time on it. However, the code for the motion tracker is available at https://ravos.netlify.app/tracker.py.

**Comment by yahooo-m** [comment]
Thanks!
