### ISSUE TITLE
Data Access denied

### ISSUE THREAD

**Issue by DeepRunner** [bo-miao/SgMg#2]
Hi, two link in [https://github.com/bo-miao/SgMg/blob/main/docs/data.md](https://github.com/bo-miao/SgMg/blob/main/docs/data.md) is deprecated and cannot be accessed, could u please update it?

[https://drive.google.com/drive/u/0/folders/1daTuACcZUKuzgl0iqzwCfKm_tSISarFl](https://drive.google.com/drive/u/0/folders/1daTuACcZUKuzgl0iqzwCfKm_tSISarFl)

[https://drive.google.com/drive/u/0/folders/1sXmjpWmc0GxYIz-EFLw5S9dJvmGJAPqx](https://drive.google.com/drive/u/0/folders/1sXmjpWmc0GxYIz-EFLw5S9dJvmGJAPqx)

**Comment by bo-miao** [comment]
Hi,

Please find the new link to the JSON files of A2D & JHMDB below.

https://drive.google.com/file/d/1oj7mt32TwnzdkalrvQJDuYxDW1K5BjRt
